language: go

sudo: false

env:
  global:
    - GO111MODULE=on
    - GOLANGCI_VER=v1.25.0

go:
  - stable

install: true

before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | bash -s -- -b $GOPATH/bin $GOLANGCI_VER

script:
  - make test
  - make lint

after_success:
  - bash <(curl -s https://codecov.io/bash)
